[project]
name = "clanto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "tqdm>=4.67.1",
    "xlsx2csv>=0.8.4",
]
