DEFAULT_ANONYMISATION_OPTIONS = {
    "random_length": 10,
    "prefix": "ANON_",
}

DATABASE_SUPPORT = ["*.db", "*.sqlite"]

FILE_SUPPORT = ["*.csv", "*.xlsx"]

RANDOM_WORDS = [
    "fizzblast",
    "sparklepop",
    "bubbleburst",
    "zingzang",
    "frothyfizz",
    "sizzlesplash",
    "popwhistle",
    "fizzwhizz",
    "sparkleburst",
    "bubblepop",
    "zingfizz",
    "frothyblast",
    "sizzlepop",
    "popfizz",
    "fizzsparkle",
    "sparklefizz",
    "bubblezing",
    "zingpop",
    "frothyfizzle",
    "sizzleburst",
    "popsparkle",
    "fizzbubble",
    "sparklezing",
    "bubblefizz",
    "zingfrothy",
    "frothyzing",
    "sizzlefizz",
    "popbubble",
    "fizzspark",
    "sparklebubble",
    "bubblefrothy",
    "zingfizzle",
    "frothybubble",
    "sizzlespark",
    "popfrothy",
    "fizzzing",
    "sparklefrothy",
    "bubblespark",
    "zingspark",
    "frothyspark",
    "sizzlezing",
    "popspark",
    "fizzfrothy",
    "sparklezing",
    "bubblezing",
    "zingbubble",
    "frothyzing",
    "sizzlebubble",
    "popzing",
]

RANDOM_CHARS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
